destination: "dist"
name: "Blog of the things"
description: "A generally tech oriented blog about things that interest it's author."
url: http://corylee.io
exclude: ["README.md", "LICENSE", ".bowerrc"]
sass:
    sass_dir: _sass
    style: :compressed
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Cory Lee"
      is_post: false
  - 
    scope: 
      path: "_drafts"
    values:
      is_post: true
  - 
    scope: 
      path: "_posts"
    values:
      is_post: true
  -
    scope:
      path: "json"
    values:
      layout: "json"

