destination: "dist"
name: "Blog of the things"
exclude: ["README.md", "LICENSE", ".bowerrc"]
sass:
    sass_dir: _sass
    style: :compressed
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Cory Lee"